name: one
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
  watch:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: De Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 're0dPacke0t'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/j2d_re0dPacke0t.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }} 
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'j0y_st0eal'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/j0y_st0eal.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }} 
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'j0dz0z'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/j0dz0z.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }}  
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'm0mbi'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/j34d_m0s.js 
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }}
            
            
            
            
            
            
