name: xxh
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  watch:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'mon0eyT0ree'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/j1d_mon0eyT0ree.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }} 
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'pi0gPe0t0'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/pi0gPe0t0.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }} 
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'chashi'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /DJSM.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }}  
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'sp0eed'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/j0d_sp0eed.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }}  
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'ddquan'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/ne0cklace0.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }}  
            
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'un0subscribe0'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/un0subscribe0.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
            EFORK: ${{ secrets.EFORK }}        

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/fully
          ref: 'master'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'cj-shoplottery'
        run: |
          node cj.js
          node shoplottery.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }}
              TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
              TG_USER_ID: ${{ secrets.TG_USER_ID }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/fully
          ref: 'master'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'gdgc'
        run: |
          node gdgc.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }}  

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/fully
          ref: 'master'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'gdnc'
        run: |
          node gdnc.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }}  

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/fully
          ref: 'master'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'gdzd'
        run: |
          node gdzd.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }} 

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/fully
          ref: 'master'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'moc'
        run: |
          node moc.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }}  

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/fully
          ref: 'master'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'xgc'
        run: |
          node xgc.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }}  

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/fully
          ref: 'master'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'xjhb'
        run: |
          node xjhb.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/you
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'try'
        run: |
          node try.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }}  
                                  
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: lajigth/you
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm install
        run: |
          npm install
      - name: 'jfd'
        run: |
          node jfd.js
        env:
              JD_COOKIE: ${{ secrets.JD_COOKIE }}
              JXNCTOKENS: ${{ secrets.JXNCTOKENS }}
              XLC: ${{ secrets.XLC }}
              GITHUB: ${{ secrets.GITHUB }}
              EFORK: ${{ secrets.EFORK }}

      - name: De Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
