name: xxh
on:
  workflow_dispatch:
  schedule:
    - cron: '36 * * * *'
  watch:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
            node-version: 12.x
      - name: npm install
        run: |
            npm install
      - name: 'mon0eyT0ree'
        run: |
            node Club.js
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SYNCURL: /The.Flash/The.Flash/j1d_mon0eyT0ree.js
            GITHUB: ${{ secrets.GITHUB }}
            HELPURL: ${{ secrets.HELPURL }}
